server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/blog
      grid-fs-database: images
logging:
  level:
    org.springframework.web: INFO

## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000