server:
  port: 8080
spring:
  data:
    mongodb:
      #      uri: ${MONGODB_URI}
      uri: mongodb://localhost:27018/pilot
      grid-fs-database: images
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
    org.springframework.web: INFO
cloudinary:
    url: ${CLOUDINARY_URL}