server:
  port: 8080
spring:
  data:
    mongodb:
      #      uri: ${MONGODB_URI}
      uri: mongodb://localhost:27018/pilot
      grid-fs-database: images
logging:
  level:
    org.springframework.web: INFO